#import = ["~/.config/alacritty/themes/themes/nightfox.toml"]
#import=["~/.config/alacritty/themes/themes/catppuccin_macchiato.toml"]
#import=["~/.config/alacritty/themes/themes/catppuccin_mocha.toml"]
#import=["~/.config/alacritty/themes/themes/cyber_punk_neon.toml"]
#import=["~/.config/alacritty/themes/themes/github_dark_dimmed.toml"]
#import=["~/.config/alacritty/themes/themes/moonlight_ii_vscode.toml"]
import=["~/.config/alacritty/themes/themes/one_dark.toml"]

[colors]
draw_bold_text_with_bright_colors = false
transparent_background_colors = false

[cursor]
blink_interval = 500
blink_timeout = 30

[cursor.style]
blinking = "On"
shape = "Beam"

[font]
size = 13.0

# Use built-in font for box drawing characters
builtin_box_drawing = true  # Default: true

normal = { family = "MesloLGS NF", style = "Regular" }
bold = { family = "MesloLGS NF", style = "Bold" }
italic = { family = "MesloLGS NF", style = "Italic" }
bold_italic = { family = "MesloLGS NF", style = "Bold Italic" }

glyph_offset = { x = 0, y = 0 }

[scrolling]
history = 10000
multiplier = 3

[window]
decorations = "Transparent"
opacity = 0.5
blur = true


[window.class]
general = "Alacritty"
instance = "Alacritty"

[window.padding]
x = 10
y = 40
